# Generated by Django 4.2 on 2023-04-26 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='download_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
