# Generated by Django 4.2 on 2023-04-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_download_count_alter_book_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.IntegerField(choices=[(1, 'Published'), (0, 'Draft')], default=0),
        ),
    ]
