# Generated by Django 4.2 on 2023-04-25 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_title',
            new_name='title',
        ),
    ]
